#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/xconnect/xconnect /usr/bin/xconnect
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/xconnect.service ]; then
			rm /etc/systemd/system/xconnect.service /usr/lib/systemd/system/xconnect.service /usr/lib/systemd/user/xconnect.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/xconnect/files/systemd/xconnect.service /usr/lib/systemd/system/xconnect.service
		# try fix error in Ubuntu 18.04
		# Failed to reload xconnect.service: Unit xconnect.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/xconnect.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/xconnect.service
		fi
		systemctl daemon-reload
		systemctl enable xconnect
		systemctl start xconnect
	fi
fi
