#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/xconnect
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop xconnect || true
			systemctl disable xconnect || true
			rm /etc/systemd/system/xconnect.service /usr/lib/systemd/system/xconnect.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'xconnect +--server' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop xconnect >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/xconnect.service >/dev/null 2>&1 || true
		fi
		
		# Remove autostart file
		rm -f /etc/xdg/autostart/xconnect.desktop || true
        ;;
esac

exit 0
